#!/usr/bin/env sh
DB_FOLDER=$HOME/develop/household-bookkeeping/dbserver/data
if [ ! -d "$DB_FOLDER" ]; then
    mkdir -p "$DB_FOLDER"
fi
docker run --name dbserver -e MYSQL_ROOT_PASSWORD=ScottT\!g3r -e MYSQL_DATABASE=ledger -e MYSQL_USER=app -e MYSQL_PASSWORD=Alm\!ghty1 -v "$DB_FOLDER":/var/lib/mysql/ledger -p 3306:3306 -d mariadb --character-set-server=utf8mb4 --character-set-client=utf8mb4  --collation-server=utf8mb4_unicode_ci
